version: '3.10'

services:
  django:
    container_name: docker_back
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - ./musicbackend:/back_proj
    ports:
      - 8086:8086
    depends_on:
      - celery
      - redis
    expose:
      - 8086

  redis:
    image: redis:alpine
    restart: always

  celery:
    restart: always
    build:
      context: .
      dockerfile: ./compose/celery/Dockerfile
    volumes:
      - ./musicbackend:/back_proj
    environment:
      - DEBUG=1
      - SECRET_KEY="django-insecure-m!b^@r&jm*49nf2u!2t@sfmv!j$xuij6^c5wnv0j9$22y86!!e"
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.01 [::1]
    depends_on:
      - redis

  celery-beat:
    restart: always
    build:
      context: .
      dockerfile: ./compose/celery-beat/Dockerfile
    volumes:
      - ./musicbackend:/back_proj
    environment:
      - DEBUG=1
      - SECRET_KEY="django-insecure-m!b^@r&jm*49nf2u!2t@sfmv!j$xuij6^c5wnv0j9$22y86!!e"
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.01 [::1]
    depends_on:
      - redis


  # flower: 
  #   build: .
  #   command: celery -A core flower
  #   ports:
  #     - 5555:5555
  #   volumes:
  #     ./musicbackend:/back_proj
  #   environment:
  #     - DEBUG=1
  #     - SECRET_KEY="django-insecure-m!b^@r&jm*49nf2u!2t@sfmv!j$xuij6^c5wnv0j9$22y86!!e"
  #     - DJANGO_ALLOWED_HOSTS=localhost 127.0.01 [::1]
  #   depends_on:
  #     - redis
  #     - celery

  front:
    container_name: docker_front
    restart: always
    build:
      context: .
      dockerfile: ./compose/front/Dockerfile
    volumes:
      - ./musical-instrument-store:/front_proj
      - /front_proj/node_modules
    ports:
      - 8080:8080
    expose:
      - 8080


  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"